services:
  db:
    image: postgres:15
    container_name: inep-db
    environment:
      - POSTGRES_USER=inep
      - POSTGRES_PASSWORD=inep
      - POSTGRES_DB=inep_db
    ports:
      - "5432:5432"
    volumes:
      - ./Data Layer/silver/ddl.sql:/docker-entrypoint-initdb.d/1_silver.sql:ro
      - ./Data Layer/gold/ddl.sql:/docker-entrypoint-initdb.d/2_gold.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inep -d inep_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inep-etl
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=inep
      - POSTGRES_PASSWORD=inep
      - POSTGRES_DB=inep_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - BRONZE_DATA_PATH=/app/Data Layer/raw/dados_brutos.csv
      - PROJECT_ROOT=/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
