services:
  db:
    image: postgres:15
    container_name: inep-db
    environment:
      - POSTGRES_USER=inep
      - POSTGRES_PASSWORD=inep
      - POSTGRES_DB=inep_db
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inep -d inep_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build:
      context: .
      dockerfile: transform/etl/Dockerfile
    container_name: inep-etl
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=inep
      - POSTGRES_PASSWORD=inep
      - POSTGRES_DB=inep_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SILVER_PARQUET_PATH=/app/processed/escolas_silver.parquet
      - BRONZE_DATA_PATH=/app/bronze/escolas_inep.csv
      - PROJECT_ROOT=/app
      - PIPELINE_NOTEBOOKS=transform/tratamento.ipynb
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
